language: python
sudo: required
dist: xenial
os:
  - linux
  - windows
python:
  - 2.7
  - 3.4
  - 3.7
install: pip install pytest
before_script:
  - ln -s `pwd` ../python_task_helper
script:
  - pytest
  - python examples/mytask.py < examples/input.json
